name: lilystefano
favicon: null
layout_spectrum: 0.0960254033561796
typography_spectrum: 0.5243872064165771
title: Lily Stefano for Mayor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.661730025196448
  lightness: 0.0983930304646492
  saturation: 0.12980760261416435
  rhythmicContrast: 0.438608106225729
purpose: []
